/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'way' at '15-3-28 上午10:23' with Gradle 2.2.1
 *
 * @author way, @date 15-3-28 上午10:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
