/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2013-07-30 14:47:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.webdatagrid;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.onetwo.common.web.config.BaseSiteConfig;
import org.onetwo.common.web.view.jsp.grid.*;

public final class pagination_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {



public String pageLink(String action, int numb){
	String result = action;
	if(numb<=1)
		return result;
	if (action.indexOf("?")!=-1){
		result += "&pageNo="+numb;
	}else{
		result += "?pageNo="+numb;
	}
	return result;
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/common/taglibs.jsp", Long.valueOf(1375068074000L));
    _jspx_dependants.put("/WEB-INF/tools.tld", Long.valueOf(1375068150000L));
    _jspx_dependants.put("/WEB-INF/spring.tld", Long.valueOf(1374558493000L));
    _jspx_dependants.put("/WEB-INF/spring-form.tld", Long.valueOf(1374558493000L));
    _jspx_dependants.put("/WEB-INF/widget.tld", Long.valueOf(1375195064000L));
    _jspx_dependants.put("/WEB-INF/layout.tld", Long.valueOf(1374739581000L));
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private org.onetwo.common.utils.Page page;
  private java.lang.String action;

  public org.onetwo.common.utils.Page getPage() {
    return this.page;
  }

  public void setPage(org.onetwo.common.utils.Page page) {
    this.page = page;
    jspContext.setAttribute("page", page);
  }

  public java.lang.String getAction() {
    return this.action;
  }

  public void setAction(java.lang.String action) {
    this.action = action;
    jspContext.setAttribute("action", action);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getPage() != null ) 
      _jspx_page_context.setAttribute("page", getPage());
    if( getAction() != null ) 
      _jspx_page_context.setAttribute("action", getAction());

    try {
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"pagination\">\n");
      out.write("<ul>\n");
      out.write("\t");

	if(page.isHasPre()){ 
      out.write("\n");
      out.write("\t\t<li><a href=\"");
      out.print( pageLink(action, 1));
      out.write("\" style=\"background:none\">首页</a></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print( pageLink(action, page.getPrePage()));
      out.write("\" style=\" background:none\">上一页</a></li>\n");
      out.write("\t");
} 
	String pageClass = "";
	for(int pageNumber=page.getStartPage(); pageNumber<=page.getEndPage(); pageNumber++){
		if(page.getPageNo()==pageNumber){
			pageClass="class='tabOn' style='font-size:18px;color:red;'";
		}else{
			pageClass="style='font-size:12px;'";
		}
	
      out.write("\n");
      out.write("\t\t<li><a href=\"");
      out.print(pageLink(action, pageNumber) );
      out.write('"');
      out.write(' ');
      out.print(pageClass);
      out.write('>');
      out.print(pageNumber );
      out.write("</a></li>\n");
      out.write("\t");

	}//end for
	
	if(page.isHasNext()){
      out.write("\n");
      out.write("\t\t<li><a href=\"");
      out.print(pageLink(action, page.getNextPage()) );
      out.write("\" style=\" background:none\">下一页</a></li>\n");
      out.write("\t\t<li><a href=\"");
      out.print(pageLink(action, page.getTotalPages()) );
      out.write("\" style=\" background:none\">尾页</a></li> \n");
      out.write("\t");
} //end if
      out.write("\n");
      out.write("</ul>\n");
      out.write(" </div>\n");
      out.write(" <div>\n");
      out.write(" 当前第 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pageNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null, false));
      out.write(" 页 ，一共 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.totalPages}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null, false));
      out.write(" 页，有 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.totalCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null, false));
      out.write(" 条数据\n");
      out.write(" </div>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
