#!/bin/bash

currentCmd="$*"

function runArgsCmdInCurrentDir(){
    # 获取当前目录的路径
    currentPath=$(cd `dirname $0`; pwd)
    echo "curent dir: $currentPath"
    echo "run cmd: $currentCmd"
    eval $currentCmd
}

cd ..
runArgsCmdInCurrentDir

cd ../dbm
runArgsCmdInCurrentDir

cd ../onetwo-wechat
runArgsCmdInCurrentDir

cd ../zifish-plugins
runArgsCmdInCurrentDir

cd ../onetwo-tcc
runArgsCmdInCurrentDir
