/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-03-05 06:57:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class application_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("t:firstNotblank", org.onetwo.common.web.view.jsp.tools.ToolEl.class, "firstNotblank", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("t:escapeHtml", org.onetwo.common.web.view.jsp.tools.ToolEl.class, "escapeHtml", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/common/taglibs.jsp", Long.valueOf(1383279669093L));
    _jspx_dependants.put("/WEB-INF/security.tld", Long.valueOf(1378347085640L));
    _jspx_dependants.put("/WEB-INF/tools.tld", Long.valueOf(1383270581218L));
    _jspx_dependants.put("/WEB-INF/spring.tld", Long.valueOf(1378347084828L));
    _jspx_dependants.put("/WEB-INF/spring-form.tld", Long.valueOf(1378347084906L));
    _jspx_dependants.put("/WEB-INF/widget.tld", Long.valueOf(1392013352560L));
    _jspx_dependants.put("/WEB-INF/layout.tld", Long.valueOf(1378347084812L));
    _jspx_dependants.put("/WEB-INF/tags/import/css.tag", Long.valueOf(1382147656125L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname.release();
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\r');
      out.write('\n');
    
response.setHeader("Cache-Control","no-cache"); //HTTP 1.1    
response.setHeader("Pragma","no-cache"); //HTTP 1.0    
response.setDateHeader ("Expires", 0); //prevents caching at the proxy server    

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t    <meta charset=\"utf-8\">\r\n");
      out.write("\t    <title>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_layout_005fdefine_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    </title>\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t    <meta name=\"description\" content=\"\">\r\n");
      out.write("\t    <meta name=\"author\" content=\"\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.jsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t  ");
      if (_jspx_meth_import_005fcss_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t  ");
      if (_jspx_meth_import_005fcss_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t  ");
      if (_jspx_meth_import_005fcss_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.cssPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.baseURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/fmtag/static/js/aa.js?t=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${now.millis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.baseURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/fmtag/static/js/table.js?t=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${now.millis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.jsPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fdefine_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_layout_005fdefine_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"showTipsModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t  <div class=\"modal-header\">\r\n");
      out.write("\t\t    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t    <h3 id=\"tipsTitle\" class=\"modal-title\">提示</h3>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"modal-body\">\r\n");
      out.write("\t\t    <p>loading……</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"modal-footer\">\r\n");
      out.write("\t\t    <button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">关闭</button>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t    \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_layout_005fdefine_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t<br style=\"clear:both; border:0px; padding:0px; margin:0px;\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("      $.jfish.initAfterPage();\r\n");
      out.write("      </script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fdefine_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:define
    org.onetwo.common.web.view.jsp.layout.DefineTag _jspx_th_layout_005fdefine_005f0 = (org.onetwo.common.web.view.jsp.layout.DefineTag) _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname.get(org.onetwo.common.web.view.jsp.layout.DefineTag.class);
    _jspx_th_layout_005fdefine_005f0.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fdefine_005f0.setParent(null);
    // /WEB-INF/views/layout/application.jsp(13,3) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fdefine_005f0.setName("title");
    int _jspx_eval_layout_005fdefine_005f0 = _jspx_th_layout_005fdefine_005f0.doStartTag();
    if (_jspx_eval_layout_005fdefine_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_layout_005fdefine_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_layout_005fdefine_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_layout_005fdefine_005f0.doInitBody();
      }
      do {
        out.write("欢迎使用市民卡运营支撑系统");
        int evalDoAfterBody = _jspx_th_layout_005fdefine_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_layout_005fdefine_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_layout_005fdefine_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname.reuse(_jspx_th_layout_005fdefine_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname.reuse(_jspx_th_layout_005fdefine_005f0);
    return false;
  }

  private boolean _jspx_meth_import_005fcss_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  import:css
    org.apache.jsp.tag.webimport_.css_tag _jspx_th_import_005fcss_005f0 = (new org.apache.jsp.tag.webimport_.css_tag());
    _jsp_instancemanager.newInstance(_jspx_th_import_005fcss_005f0);
    _jspx_th_import_005fcss_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/views/layout/application.jsp(20,3) name = path type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f0.setPath("/bootstrap/css/bootstrap");
    // /WEB-INF/views/layout/application.jsp(20,3) name = min type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f0.setMin(new java.lang.Boolean(true));
    // /WEB-INF/views/layout/application.jsp(20,3) name = dev type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f0.setDev((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.dev}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_import_005fcss_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_import_005fcss_005f0);
    return false;
  }

  private boolean _jspx_meth_import_005fcss_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  import:css
    org.apache.jsp.tag.webimport_.css_tag _jspx_th_import_005fcss_005f1 = (new org.apache.jsp.tag.webimport_.css_tag());
    _jsp_instancemanager.newInstance(_jspx_th_import_005fcss_005f1);
    _jspx_th_import_005fcss_005f1.setJspContext(_jspx_page_context);
    // /WEB-INF/views/layout/application.jsp(21,3) name = path type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f1.setPath("/bootstrap/css/bootstrap-responsive");
    // /WEB-INF/views/layout/application.jsp(21,3) name = min type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f1.setMin(new java.lang.Boolean(true));
    // /WEB-INF/views/layout/application.jsp(21,3) name = dev type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f1.setDev((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.dev}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_import_005fcss_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_import_005fcss_005f1);
    return false;
  }

  private boolean _jspx_meth_import_005fcss_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  import:css
    org.apache.jsp.tag.webimport_.css_tag _jspx_th_import_005fcss_005f2 = (new org.apache.jsp.tag.webimport_.css_tag());
    _jsp_instancemanager.newInstance(_jspx_th_import_005fcss_005f2);
    _jspx_th_import_005fcss_005f2.setJspContext(_jspx_page_context);
    // /WEB-INF/views/layout/application.jsp(23,3) name = path type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f2.setPath("/admin/assets/styles");
    // /WEB-INF/views/layout/application.jsp(23,3) name = min type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f2.setMin(new java.lang.Boolean(false));
    // /WEB-INF/views/layout/application.jsp(23,3) name = dev type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_import_005fcss_005f2.setDev((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteConfig.dev}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_import_005fcss_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_import_005fcss_005f2);
    return false;
  }

  private boolean _jspx_meth_layout_005fdefine_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:define
    org.onetwo.common.web.view.jsp.layout.DefineTag _jspx_th_layout_005fdefine_005f1 = (org.onetwo.common.web.view.jsp.layout.DefineTag) _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody.get(org.onetwo.common.web.view.jsp.layout.DefineTag.class);
    _jspx_th_layout_005fdefine_005f1.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fdefine_005f1.setParent(null);
    // /WEB-INF/views/layout/application.jsp(29,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fdefine_005f1.setName("jsscript");
    int _jspx_eval_layout_005fdefine_005f1 = _jspx_th_layout_005fdefine_005f1.doStartTag();
    if (_jspx_th_layout_005fdefine_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody.reuse(_jspx_th_layout_005fdefine_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody.reuse(_jspx_th_layout_005fdefine_005f1);
    return false;
  }

  private boolean _jspx_meth_layout_005fdefine_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:define
    org.onetwo.common.web.view.jsp.layout.DefineTag _jspx_th_layout_005fdefine_005f2 = (org.onetwo.common.web.view.jsp.layout.DefineTag) _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody.get(org.onetwo.common.web.view.jsp.layout.DefineTag.class);
    _jspx_th_layout_005fdefine_005f2.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fdefine_005f2.setParent(null);
    // /WEB-INF/views/layout/application.jsp(30,1) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fdefine_005f2.setName("cssscript");
    int _jspx_eval_layout_005fdefine_005f2 = _jspx_th_layout_005fdefine_005f2.doStartTag();
    if (_jspx_th_layout_005fdefine_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody.reuse(_jspx_th_layout_005fdefine_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname_005fnobody.reuse(_jspx_th_layout_005fdefine_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/layout/application.jsp(48,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message || not empty param.message}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<div class=\"alert alert-");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t:firstNotblank(messageType, param.messageType, 'block')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
        out.write("  alert-dismissable\">\r\n");
        out.write("  \t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>\r\n");
        out.write("  \t\t\t\t<strong>提示!</strong>\r\n");
        out.write("\t\t\t\t");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t:escapeHtml(message)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1, false));
        out.write("\r\n");
        out.write("\t\t\t  \t");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t:escapeHtml(param.message)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1, false));
        out.write("\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t\t<script type=\"text/javascript\">\r\n");
        out.write("\t\t\t\t$(function() {\r\n");
        out.write("\t\t\t\t\t$(\".alert\").stop().fadeTo(1,0).fadeTo(2000,0.9).delay(1000).fadeTo(1000,0);\r\n");
        out.write("\t\t\t\t})\r\n");
        out.write("\t\t\t</script>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_layout_005fdefine_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:define
    org.onetwo.common.web.view.jsp.layout.DefineTag _jspx_th_layout_005fdefine_005f3 = (org.onetwo.common.web.view.jsp.layout.DefineTag) _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname.get(org.onetwo.common.web.view.jsp.layout.DefineTag.class);
    _jspx_th_layout_005fdefine_005f3.setPageContext(_jspx_page_context);
    _jspx_th_layout_005fdefine_005f3.setParent(null);
    // /WEB-INF/views/layout/application.jsp(62,3) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_layout_005fdefine_005f3.setName("main-content");
    int _jspx_eval_layout_005fdefine_005f3 = _jspx_th_layout_005fdefine_005f3.doStartTag();
    if (_jspx_eval_layout_005fdefine_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_layout_005fdefine_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_layout_005fdefine_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_layout_005fdefine_005f3.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t页面详细内容\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_layout_005fdefine_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_layout_005fdefine_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_layout_005fdefine_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname.reuse(_jspx_th_layout_005fdefine_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005flayout_005fdefine_0026_005fname.reuse(_jspx_th_layout_005fdefine_005f3);
    return false;
  }
}
