{"sheets":[{"name":"报名客户资料报表",
	"rows":[{"name":"entity","type":"iterator","space":0,"span":"0","height":0,
		"renderHeader":true,
		"datasource":"#data",
		"fields":[
		          {"label":"主键","name":"id","value":"id","colspan":"1","rowspan":"1"},
		          {"label":"卡号","name":"cardNo","value":"cardNo","colspan":"1","rowspan":"1"},
		          {"label":"卡密码","name":"cardPwd","value":"cardPwd","colspan":"1","rowspan":"1"}
		          ],"iterator":true}
	]
		        	  }]}