<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="layout" uri="/WEB-INF/layout.tld" %> 
<%@ taglib prefix="widget" uri="/WEB-INF/widget.tld" %> 
<%@ taglib prefix="t" uri="/WEB-INF/tools.tld" %> 
<%@ taglib prefix="import" tagdir="/WEB-INF/tags/import" %>
<%@ taglib prefix="security" uri="/WEB-INF/security.tld" %>
<%@ taglib prefix="aa" uri="http://ajaxanywhere.sourceforge.net/" %>
